[tool.poetry]
name = "django-tutorial"
version = "0.1.0"
description = ""
authors = ["Erik S. Carlsten <ecarlste@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Django = "3.0"
pytz = "2019.3"
sqlparse = "0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
